### ISSUE TITLE
connect_to localhost port 7860: failed.

### ISSUE THREAD

**Issue by z0ranzhang** [facefusion/facefusion-colab#1]
Traceback (most recent call last):
  File "/content/facefusion/run.py", line 3, in <module>
    from facefusion import core
  File "/content/facefusion/facefusion/core.py", line 18, in <module>
    import facefusion.choices
  File "/content/facefusion/facefusion/choices.py", line 3, in <module>
    from facefusion.typing import FaceRecognition, FaceAnalyserDirection, FaceAnalyserAge, FaceAnalyserGender, TempFrameFormat, OutputVideoEncoder
  File "/content/facefusion/facefusion/typing.py", line 2, in <module>
    from insightface.app.common import Face
  File "/usr/local/lib/python3.10/dist-packages/insightface/__init__.py", line 16, in <module>
    from . import model_zoo
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/model_zoo.py", line 22, in <module>
    class PickableInferenceSession(onnxruntime.InferenceSession): 
AttributeError: module 'onnxruntime' has no attribute 'InferenceSession'
connect_to localhost port 7860: failed.
connect_to localhost port 7860: failed.

**Comment by henryruhs** [comment]
Destroy the whole runtime and start it again... the download of the models gone wrong.
